blank_issues_enabled: false
contact_links:
  - name: Have any issues to discuss regarding Coding Blocks?
    url: https://discord.com/channels/508572416587464704/710924517878530239
    about: Join us on Gitter and meet members, contributors and the owners!
